spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://techloom-ecommerce-db.ci9cqyeusu3o.us-east-1.rds.amazonaws.com:5432/techloom_pos
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081